"""Final whiskey_token update

Revision ID: 7c96a5320c67
Revises: 2fd414aaeb77
Create Date: 2023-06-10 18:58:22.976002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c96a5320c67'
down_revision = '2fd414aaeb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.alter_column('whiskey_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.drop_constraint('whiskey_whiskey_token_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.create_unique_constraint('whiskey_whiskey_token_key', ['whiskey_token'])
        batch_op.alter_column('whiskey_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
