"""Updated whiskey_token

Revision ID: edbd51c6e46a
Revises: 7c96a5320c67
Create Date: 2023-06-10 20:01:49.684846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbd51c6e46a'
down_revision = '7c96a5320c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.alter_column('whiskey_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.alter_column('whiskey_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
